# Generated by Django 3.1.13 on 2022-01-03 13:07

import accounts.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessClientUser',
            fields=[
                ('clientuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.clientuser')),
                ('organization_name', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'BusinessClient',
                'verbose_name_plural': 'BusinessClients',
            },
            bases=('accounts.clientuser',),
        ),
        migrations.AlterField(
            model_name='clientuser',
            name='first_name',
            field=models.CharField(max_length=32, validators=[accounts.validators.first_name_validator]),
        ),
        migrations.AlterField(
            model_name='clientuser',
            name='last_name',
            field=models.CharField(max_length=32, validators=[accounts.validators.last_name_validator]),
        ),
    ]
