# Generated by Django 3.1.13 on 2022-01-05 15:22

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='first_name',
            field=models.CharField(max_length=32, validators=[accounts.validators.first_name_validator]),
        ),
        migrations.AlterField(
            model_name='clientuser',
            name='last_name',
            field=models.CharField(max_length=32, validators=[accounts.validators.last_name_validator]),
        ),
    ]
