# Generated by Django 3.1.13 on 2022-01-09 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220105_1522'),
        ('accounts', '0002_auto_20220103_1307'),
    ]

    operations = [
    ]
