# Generated by Django 3.1.13 on 2022-01-11 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_20220109_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessclientuser',
            options={'ordering': ('organization_name',), 'verbose_name': 'BusinessClient', 'verbose_name_plural': 'BusinessClients'},
        ),
    ]
