# Generated by Django 3.1.13 on 2022-02-15 11:44

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220111_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_url', models.ImageField(upload_to=accounts.models.upload_to)),
            ],
        ),
        migrations.AddField(
            model_name='clientuser',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_user', to='accounts.avatar'),
        ),
    ]
