# Docker-compose configuration for development environment on server

version: '3.7'

services:
  booking_nginx:
    build:
      context: .
      dockerfile: Dockerfile-node.production
    container_name: booking_nginx
    ports:
      - "80:80"
    depends_on:
      - booking_django
    volumes:
      - "./app:/usr/src/app"
      - "./app/node_modules:/usr/src/app/node_modules"
      - "./nginx:/etc/nginx"
      - "./backend/staticfiles:/usr/share/nginx/html/static-backend"
      - "./backend/media:/usr/share/nginx/html/media"
    networks:
      - booking_production_services

  booking_django:
    image: django
    container_name: booking_django
    build:
      context: .
      dockerfile: Dockerfile-django.production
    ports:
      - "3000:3000"
    volumes:
      - "./backend:/app"
    environment:
      - PYTHONUNBUFFERED=1
    env_file: .env
    depends_on:
      - booking_postgres
    networks:
      - booking_production_services

  booking_postgres:
    image: postgres:13
    container_name: booking_postgres
    volumes:
      - ".data/postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: booking
      POSTGRES_USER: booking
      POSTGRES_PASSWORD: booking
    ports:
      - "5432:5432"
    networks:
      - booking_production_services


networks:
  booking_production_services:
    name: booking_production_services
    driver: bridge
