# Development Dockerfile for Django app
FROM python:3.9-slim

ENV PYTHONUNBUFFERED 1

# Expose our application port
EXPOSE 3000

# Install system requirements & Python dependencies
RUN set -xe \
 && apt-get update -q \
 && apt-get install -y --no-install-recommends gettext poppler-utils\
 && apt-get autoremove -y \
 && apt-get clean -y \
 && rm -rf /var/lib/apt/lists/*

# Install all POSTGIS requirements
RUN apt-get update && apt-get install -y \
    binutils \
    libproj-dev \
    gdal-bin \
    && rm -rf /var/lib/apt/lists/*

COPY ./requirements.txt /

# Install all dependencies from requirements.txt file
RUN pip install -r requirements.txt

# Set the default directory where CMD will execute
WORKDIR /app

# Run Django's runserver by default
CMD python manage.py runserver 0.0.0.0:8000
