# Based on Node 10 Alpine image
FROM node:16.13.1

# Set the default directory where CMD will execute
WORKDIR /app

# Expose our application ports
EXPOSE 3000

ARG COMMIT_HASH
ENV RAZZLE_COMMIT_HASH=$COMMIT_HASH

# Set the default command to execute when creating a new container
CMD /bin/bash -c "npm install && npm run start"