FROM node:16.13.1 as builder

# Set the default directory where CMD will execute
WORKDIR /usr/src/app

COPY ./app/package.json ./app/yarn.lock ./

# Set the default command to execute when creating a new container
RUN yarn

COPY ./app ./

RUN yarn build

FROM nginx:1.17

COPY ./nginx/ /etc/nginx/

# Remove default nginx index page
RUN rm -rf /usr/share/nginx/html/*

# Copy from the stage 1
COPY --from=builder /usr/src/app/build /usr/share/nginx/html

ENTRYPOINT ["nginx", "-g", "daemon off;"]
