# Docker-compose configuration for development environment on server

version: '3.7'

services:
  booking_nginx:
    build:
      context: .
      dockerfile: Dockerfile-node.production
    ports:
      - "80:80"
    depends_on:
      - booking_django
    volumes:
      - "./app:/usr/src/app"
      - "./app/node_modules:/usr/src/app/node_modules"
      - "./nginx:/etc/nginx"

  booking_django:
    image: django
    build:
      context: .
      dockerfile: Dockerfile-django.production
    ports:
      - "3000:3000"
    environment:
      - PYTHONUNBUFFERED=1
    env_file: .env
    depends_on:
      - booking_postgres
    container_name: booking_django
    networks:
      - booking_local_services

  booking_postgres:
    image: postgres:13
    volumes:
      - ".data/postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: booking
      POSTGRES_USER: booking
      POSTGRES_PASSWORD: booking
    container_name: booking_postgres
    ports:
      - "5432:5432"
    networks:
      - booking_local_services


networks:
  booking_local_services:
    name: booking_local_services
    driver: bridge
