# Generated by Django 3.1.13 on 2022-02-09 13:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentgeowrapper',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddIndex(
            model_name='apartmentgeowrapper',
            index=models.Index(fields=['location'], name='search_apar_locatio_d2c281_idx'),
        ),
    ]
