# Generated by Django 3.1.13 on 2021-12-29 11:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('price', models.PositiveIntegerField(db_index=True)),
                ('img', models.ImageField(upload_to='apartments/')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('description', models.TextField()),
                ('num_of_bedrooms', models.PositiveIntegerField(default=2)),
                ('rating', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-rating',),
            },
        ),
    ]
