# Generated by Django 3.1.13 on 2022-01-03 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220103_1307'),
        ('apartments', '0002_apartment_business_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='business_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='accounts.businessclientuser'),
        ),
    ]
