# Generated by Django 3.1.13 on 2022-01-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_auto_20220103_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='title',
            field=models.TextField(unique=True),
        ),
    ]
