# Generated by Django 3.1.13 on 2022-01-10 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_auto_20220105_1239'),
        ('apartments', '0003_auto_20220109_2001'),
    ]

    operations = [
    ]
