# Generated by Django 3.1.13 on 2022-01-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0005_merge_20220110_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='title',
            field=models.TextField(),
        ),
    ]
