# Generated by Django 3.1.13 on 2022-01-11 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220111_1556'),
        ('apartments', '0006_auto_20220110_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='business_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='accounts.businessclientuser'),
        ),
    ]
