# Generated by Django 3.1.13 on 2022-01-12 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0008_auto_20220111_1630'),
        ('apartments', '0007_booking_business_client'),
    ]

    operations = [
    ]
