# Generated by Django 3.1.13 on 2022-01-12 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0009_merge_20220112_1301'),
        ('apartments', '0008_auto_20220112_0814'),
    ]

    operations = [
    ]
