# Generated by Django 3.1.13 on 2022-01-12 17:36

import apartments.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0009_merge_20220112_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='num_of_bedrooms',
        ),
        migrations.AddField(
            model_name='apartment',
            name='feature',
            field=models.JSONField(blank=True, null=True, validators=[apartments.validators.JSONSchemaValidator(limit_value={'properties': {'bathrooms': {'type': 'number'}, 'bedrooms': {'type': 'number'}, 'beds': {'type': 'number'}, 'guests': {'type': 'number'}}, 'required': ['guests', 'bedrooms', 'beds', 'bathrooms'], 'type': 'object'})]),
        ),
    ]
