# Generated by Django 3.1.13 on 2022-01-13 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0010_merge_20220112_1313'),
        ('apartments', '0010_auto_20220112_1736'),
    ]

    operations = [
    ]
