# Generated by Django 3.1.13 on 2022-01-14 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0011_auto_20220113_1613'),
        ('apartments', '0011_merge_20220113_1633'),
    ]

    operations = [
    ]
