# Generated by Django 3.1.13 on 2022-01-14 14:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220111_1556'),
        ('apartments', '0012_merge_20220114_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.apartment')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.clientuser')),
            ],
        ),
    ]
