# Generated by Django 3.1.13 on 2022-01-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0013_apartmentreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartmentreview',
            old_name='rating',
            new_name='rate',
        ),
        migrations.AlterField(
            model_name='booking',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
