# Generated by Django 3.1.13 on 2022-01-17 16:19

import apartments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0014_auto_20220117_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=apartments.models.apartment_directory_path)),
            ],
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='img',
        ),
        migrations.AddField(
            model_name='apartment',
            name='img_content',
            field=models.ManyToManyField(blank=True, related_name='img_content', to='apartments.ApartmentsImage'),
        ),
    ]
