# Generated by Django 3.1.13 on 2022-01-17 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0015_auto_20220117_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentsimage',
            name='apartments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='apartments.apartment'),
        ),
    ]
