# Generated by Django 3.1.13 on 2022-01-19 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0016_apartmentsimage_apartments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='img_content',
        ),
        migrations.AlterField(
            model_name='apartmentsimage',
            name='apartments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='img_content', to='apartments.apartment'),
        ),
    ]
