# Generated by Django 3.1.13 on 2022-01-26 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0017_auto_20220119_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='booking',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='apartments.apartment'),
        ),
    ]
