# Generated by Django 3.1.13 on 2022-01-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0018_auto_20220126_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='user',
            field=models.ManyToManyField(related_name='favorite_apartments', to='accounts.ClientUser'),
        ),
    ]
