# Generated by Django 3.1.13 on 2022-02-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220111_1556'),
        ('apartments', '0019_apartment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='favorite_apartments', to='accounts.ClientUser'),
        ),
    ]
