# Generated by Django 3.1.13 on 2022-02-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0020_auto_20220202_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
