# Generated by Django 3.1.13 on 2022-02-17 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0021_apartment_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='is_favorite',
        ),
    ]
