# Generated by Django 3.1.13 on 2022-02-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0022_remove_apartment_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
